export const workDomainOptions = [
  {
    label: "LLM Engineer",
    value: "LLM Engineer",
  },
  { label: "Backend Developer", value: "Backend Developer" },
  { label: "Big Data Engineer", value: "Big Data Engineer" },
  { label: "Blockchain Developer", value: "Blockchain Developer" },
  { label: "Brand Specialist", value: "Brand Specialist" },
  { label: "Business Analyst", value: "Business Analyst" },
  { label: "Business Development", value: "Business Development" },
  { label: "Cloud Engineer", value: "Cloud Engineer" },
  { label: "Community Management", value: "Community Management" },
  { label: "Content Analyst", value: "Content Analyst" },
  { label: "Content Writer", value: "Content Writer" },
  { label: "Customer success", value: "Customer success" },
  { label: "Data Analyst", value: "Data Analyst" },
  { label: "Data Engineer", value: "Data Engineer" },
  { label: "Data Entry", value: "Data Entry" },
  { label: "Data Science", value: "Data Science" },
  { label: "DevOps Engineer", value: "DevOps Engineer" },
  {
    label: "Developer Advocate (DevRel)",
    value: "Developer Advocate (DevRel)",
  },
  { label: "Digital Marketing", value: "Digital Marketing" },
  { label: "Embedded Software Engineer", value: "Embedded Software Engineer" },
  { label: "Fashion Design", value: "Fashion Design" },
  { label: "Finance", value: "Finance" },
  { label: "Founder's office", value: "Founder's office" },
  { label: "Frontend Developer", value: "Frontend Developer" },
  { label: "Fullstack Developer", value: "Fullstack Developer" },
  { label: "Game Developer", value: "Game Developer" },
  { label: "Graphic Design", value: "Graphic Design" },
  { label: "Growth", value: "Growth" },
  { label: "Human Resources (HR)", value: "Human Resources (HR)" },
  {
    label: "Integration Support Engineer",
    value: "Integration Support Engineer",
  },
  { label: "Law", value: "Law" },
  { label: "Legal Consultant", value: "Legal Consultant" },
  { label: "MLOps Engineer", value: "MLOps Engineer" },
  { label: "Machine Learning Engineer", value: "Machine Learning Engineer" },
  { label: "Management Consultant", value: "Management Consultant" },
  { label: "Market/Business Research", value: "Market/Business Research" },
  { label: "Marketing", value: "Marketing" },
  { label: "Marketing/Sales", value: "Marketing/Sales" },
  { label: "Mobile App Developer", value: "Mobile App Developer" },
  { label: "NGO", value: "NGO" },
  { label: "Network Engineer", value: "Network Engineer" },
  { label: "Operations", value: "Operations" },
  { label: "Product Management", value: "Product Management" },
  { label: "Product Operations", value: "Product Operations" },
  { label: "Product marketing", value: "Product marketing" },
  { label: "Prompt Engineer", value: "Prompt Engineer" },
  { label: "Public Relations (PR)", value: "Public Relations (PR)" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "Social Media Marketing", value: "Social Media Marketing" },
  { label: "Software Developer", value: "Software Developer" },
  {
    label: "Software Development Engineer in Test (SDET)",
    value: "Software Development Engineer in Test (SDET)",
  },
  { label: "Solution Analyst", value: "Solution Analyst" },
  { label: "Strategy", value: "Strategy" },
  {
    label: "Subject Matter Expert (SME)",
    value: "Subject Matter Expert (SME)",
  },
  {
    label: "Supply Chain Management (SCM)",
    value: "Supply Chain Management (SCM)",
  },
  { label: "Teaching Assistant (TA)", value: "Teaching Assistant (TA)" },
  { label: "Technical Content Engineer", value: "Technical Content Engineer" },
  { label: "Technical Content Writer", value: "Technical Content Writer" },
  { label: "Technical Operations", value: "Technical Operations" },
  { label: "Technical Product Manager", value: "Technical Product Manager" },
  { label: "Testing Engineer", value: "Testing Engineer" },
  { label: "UI/UX Designer", value: "UI/UX Designer" },
  { label: "Video/Graphics Editing", value: "Video/Graphics Editing" },
  { label: "Volunteer", value: "Volunteer" },
  { label: "Wordpress Developer", value: "Wordpress Developer" },
];

export const degreeOptions = [
  { label: "B. Voc", value: "B. Voc" },
  { label: "B.A.", value: "B.A." },
  { label: "B.Arch", value: "B.Arch" },
  { label: "B.B.A.", value: "B.B.A." },
  { label: "B.C.A.", value: "B.C.A." },
  { label: "B.Com.", value: "B.Com." },
  { label: "B.E.", value: "B.E." },
  { label: "B.F.Tech.", value: "B.F.Tech." },
  { label: "B.Pharm.", value: "B.Pharm." },
  { label: "B.S.", value: "B.S." },
  { label: "B.Sc.", value: "B.Sc." },
  { label: "B.Tech", value: "B.Tech" },
  { label: "B.Tech + M.Tech", value: "B.Tech + M.Tech" },
  {
    label: "Bachelor of Fine Arts (BFA)",
    value: "Bachelor of Fine Arts (BFA)",
  },
  { label: "Diploma", value: "Diploma" },
  { label: "M. Voc", value: "M. Voc" },
  { label: "M.Arch", value: "M.Arch" },
  { label: "M.B.A.", value: "M.B.A." },
  { label: "M.C.A.", value: "M.C.A." },
  { label: "M.Com.", value: "M.Com." },
  { label: "M.Des.", value: "M.Des." },
  { label: "M.E.", value: "M.E." },
  { label: "M.Ed.", value: "M.Ed." },
  { label: "M.F.Tech.", value: "M.F.Tech." },
  { label: "M.S.", value: "M.S." },
  { label: "M.Sc.", value: "M.Sc." },
  { label: "M.Tech", value: "M.Tech" },
  { label: "PG Diploma", value: "PG Diploma" },
];

export const socialProfilesOptions = [
  {
    label: "Github",
    value: "Github",
  },
  {
    label: "LinkedIn",
    value: "LinkedIn",
  },
  {
    label: "Hacker Rank",
    value: "Hacker Rank",
  },
  {
    label: "GeeksforGeeks",
    value: "GeeksforGeeks",
  },
  {
    label: "CodeChef",
    value: "CodeChef",
  },
  {
    label: "LeetCode",
    value: "LeetCode",
  },
  {
    label: "Codeforces",
    value: "Codeforces",
  },
  {
    label: "Topcoder",
    value: "Topcoder",
  },
  {
    label: "Hackerearth",
    value: "Hackerearth",
  },
  {
    label: "Behance",
    value: "Behance",
  },
  {
    label: "Blog",
    value: "Blog",
  },
  {
    label: "Portfolio Website",
    value: "Portfolio Website",
  },
  {
    label: "Dribble",
    value: "Dribble",
  },
  {
    label: "Other Profile Link",
    value: "Other Profile Link",
  },
];

export const jobTypeOptions = [
  { label: "Full Time", value: "FULL_TIME" },
  { label: "Part Time", value: "PART_TIME" },
  { label: "Internship", value: "SEMI_PART_TIME" },
];

export const linksOptions = [
  { label: "Social Media", value: "Social" },
  { label: "Github", value: "Github" },
  { label: "Website", value: "Website" },
];

export const techProjectLinkOptions = [
  { label: "Demo", value: "Demo" },
  { label: "Source Code", value: "SourceCode" },
  { label: "Website", value: "Website" },
];
